include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = PicaDemo
PicaDemo_OBJCFLAGS += -fobjc-arc -I../PicaKit
PicaDemo_OBJC_FILES = main.m
PicaDemo_TOOL_LIBS += -lPicaKit
PicaDemo_NEEDS_GUI = yes

include $(GNUSTEP_MAKEFILES)/tool.make
