#import <Foundation/Foundation.h>

NSArray<NSString *> *PicaRunParserChecks(void);
NSArray<NSString *> *PicaRunExpressionChecks(void);
NSArray<NSString *> *PicaRunExpressionLangChecks(void);
NSArray<NSString *> *PicaRunLayoutChecks(void);
NSArray<NSString *> *PicaRunTablixChecks(void);
NSArray<NSString *> *PicaRunTablixGroupChecks(void);
NSArray<NSString *> *PicaRunBandEnumerationChecks(void);
NSArray<NSString *> *PicaRunTablixRebuildChecks(void);
NSArray<NSString *> *PicaRunDocumentChecks(void);
NSArray<NSString *> *PicaRunUndoChecks(void);
NSArray<NSString *> *PicaRunEditorTablixChecks(void);
NSArray<NSString *> *PicaRunSelectionChecks(void);
NSArray<NSString *> *PicaRunInsertionChecks(void);
NSArray<NSString *> *PicaRunItemTransferChecks(void);
NSArray<NSString *> *PicaRunTextAttributeChecks(void);
NSArray<NSString *> *PicaRunRichTextCodecChecks(void);
NSArray<NSString *> *PicaRunCompletionChecks(void);
NSArray<NSString *> *PicaRunEditingContextChecks(void);
NSArray<NSString *> *PicaRunTablixEditingChecks(void);
NSArray<NSString *> *PicaRunTablixAdvancedChecks(void);
NSArray<NSString *> *PicaRunHTMLBackendChecks(void);
NSArray<NSString *> *PicaRunPDFBackendChecks(void);
NSArray<NSString *> *PicaRunBackendRegistryChecks(void);
NSArray<NSString *> *PicaRunRDLSubsetChecks(void);
NSArray<NSString *> *PicaRunRDLSubset2Checks(void);
NSArray<NSString *> *PicaRunRichTextChecks(void);
NSArray<NSString *> *PicaRunAllChecks(void);
